package com.lnu.coronacitybot.entity.enums;

public interface State {
    String INITIAL = "INITIAL";
    String MENU = "MENU";
    String SUBSCRIPTION_RATE = "SUBSCRIPTION_RATE";
    String SUBSCRIPTION_TYPE = "SUBSCRIPTION_TYPE";
    String LOCATION = "LOCATION";
    String LOCATION_FOR_STATISTIC = "LOCATION_FOR_STATISTIC";
    String SUBSCRIPTION_TYPE_FOR_STATISTIC = "SUBSCRIPTION_TYPE_FOR_STATISTIC";
    String LANGUAGE = "LANGUAGE";
}
